### PR TITLE
Add AWS Lambda in Action book

### PR DESCRIPTION
**Pull request by danilop**
## Review the Contributing Guidelines

Before submitting a pull request, verify it meets all requirements in the [Contributing Guidelines](https://github.com/donnemartin/awesome-aws/blob/master/CONTRIBUTING.md).
## Describe Why This Is Awesome

Why is this awesome?

Well, it is my book :) I put a lot of energy and effort in writing a developer-oriented introduction to AWS Lambda and serverless computing.
## 

Like this pull request?  Vote for it by adding a :+1:

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi @danilop, thanks for the pull request!  Looks like this book isn't available yet.  I'll keep this open to see what the community thinks once it's out.

**Comment by danilop** [comment]
Hi, the book is already available in early access from Manning, the first
chapter is available for free.

The final version will be out end of November / beginning of December.

**Comment by danilop** [comment]
The book is now out in all formats (printed and electronics) - can we move forward? Thanks!

**Comment by donnemartin** [comment]
Thanks @danilop, and congrats on the book!

**Comment by danilop** [comment]
Thank you @donnemartin !

**Pull request merged**
