### PR TITLE
add s3renity to JavaScript related repos

### PR DESCRIPTION
**Pull request by wellsjo**

### CODE REVIEW

**Comment by donnemartin** [comment]
Thanks for the pull request!  I think this should go to the following section in alphabetical order:

https://github.com/donnemartin/awesome-aws#s3

**Comment by wellsjo** [comment]
updated!

**Comment by donnemartin** [comment]
I just realized there's no description like the other repos.  Do you mind adding one?  Thanks!

**Comment by wellsjo** [comment]
ah okay, added one!

**Comment by donnemartin** [comment]
Thank you!

**Pull request merged**
