### PR TITLE
Add yas3fs - Yet Another S3-backed File System, inspired by s3fs

### PR DESCRIPTION
**Pull request by ryanmurakami**

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi @ryanmurakami, can you break this up into separate pull requests?  Thanks!

**Comment by ryanmurakami** [comment]
@donnemartin Sure, no problem!

**Comment by donnemartin** [comment]
@ryanmurakami thanks for breaking these up, can you insert danilop/yas3fs in sorted order?

**Comment by ryanmurakami** [comment]
@donnemartin done

**Comment by donnemartin** [comment]
Thank you!

**Pull request merged**
