### PR TITLE
added books section

### PR DESCRIPTION
**Pull request by michaelwittig**
Hi,
I added a section about AWS related books. 
What do you think?

### CODE REVIEW

**Comment by donnemartin** [comment]
@michaelwittig thanks for the pull request and congrats on the new book!  It seems the book is doing well so far in terms of sales but I don't see any customer reviews yet.  I'll leave this open until we can get some reviews and to give others an opportunity to share their thoughts here.

**Comment by michaelwittig** [comment]
@donnemartin sure. There is also coming something new from O'Reilly http://shop.oreilly.com/product/0636920027638.do but it is not yet published (but early access is available)

**Comment by michaelwittig** [comment]
@donnemartin we have 3 times 5starts now :)

**Comment by donnemartin** [comment]
@michaelwittig congrats, the book seems to be doing well.  

For the pull request, it looks like you only updated the label in the Index for:

>Guides, Documentation, and Training

Can you update the section header and anchor as well?  Lines 94, 941.

**Comment by michaelwittig** [comment]
@donnemartin done

**Comment by donnemartin** [comment]
@michaelwittig thanks for the contribution!

**Comment by michaelwittig** [comment]
@donnemartin thanks for maintaining the project ;)

**Pull request merged**
