### PR TITLE
Adding Aws pluralsight classes

### PR DESCRIPTION
**Pull request by ryanmurakami**
## Describe Why This Is Awesome

The courses add an easy way for new AWS users to learn it.
## 

Like this pull request?  Vote for it by adding a :+1:

### CODE REVIEW

**Comment by donnemartin** [comment]
Thanks for the pull request!  I guess I'll have to do a trial account to check out the videos?  Unfortunately it looks like I can't even see the reviews, seems highly rated.

**Comment by ryanmurakami** [comment]
@donnemartin Yes, they do require a subscription. I wasn't sure if you were interested in paid content for the list or not, but I'm giving it a shot. :-)

**Comment by troymarshall** [comment]
There are several other very good AWS courses on Pluralsight. I have a playlist containing 11 courses that I am going through now. https://www.pluralsight.com/search?q=AWS&categories=all

**Comment by donnemartin** [comment]
Thanks for the feedback.  Curious how others feel about adding paid content to this list.  Feel free to add your thoughts or to vote for this PR.

>Like this pull request? Vote for it by adding a 👍

**Pull request closed without merging**
